### ISSUE TITLE
Add a step that shows gitops in action

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/wks-quickstart-firekube#11]
Once the cluster is up and running we should be able to demo gitops by telling the user to add a manifest to their fork and observe it being deployed to the cluster.

**Comment by palemtnrider** [comment]
@dlespiau I could add the steps I did to get podinfo running in my cluster if that offloads you.

**Comment by dlespiau** [comment]
See https://github.com/weaveworks/wks-quickstart-firekube/pull/25
