### ISSUE TITLE
Typo in README?

### ISSUE THREAD

**Issue by alexellis** [weaveworks/wks-quickstart-firekube#42]
```
kubectl apply --dry-run -k github.com/stefanprodan/podinfo//kustomize -o yaml > podinfo.yaml
git add podinfo.yaml
git commit -a -m 'Add podinfo Deployment'
git push
```

Is there meant to be a double `/` in the URL?

**Comment by Mhart12** [comment]
Nope, it's meant to be there. It won't work if you remove the extra forward slash. It's basically there to shorten the full path.

**Comment by alexellis** [comment]
Good to know. Will close.
