### ISSUE TITLE
We don't actually use the wks-controller manifest from the repository

### ISSUE THREAD

**Issue by dlespiau** [weaveworks/wks-quickstart-firekube#8]
Well, at least we can't update it.

The flux logs show:

```
system:configmap/docker: running kubectl: Error from server (NotFound): error when creating "STDIN": namespaces "system" not found
system:configmap/repo: running kubectl: Error from server (NotFound): error when creating "STDIN": namespaces "system" not found
system:deployment/wks-controller: running kubectl: Error from server (NotFound): error when creating "STDIN": namespaces "system" not found
```

That's because the manifests in the git repository are defined to run in `namespace: system` but should really be in `weavek8sops`.

Unfortunately, just changing this doesn't work either. The controller does start but can't spin up any other nodes:

```diff
diff --git a/docker-config.yaml b/docker-config.yaml
index 2f0f164..7c8529c 100644
--- a/docker-config.yaml
+++ b/docker-config.yaml
@@ -2,7 +2,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: docker
-  namespace: system
+  namespace: weavek8sops
 data:
   daemon.json: |
     {
diff --git a/repo-config.yaml b/repo-config.yaml
index 0e14c8e..5ca9aa9 100644
--- a/repo-config.yaml
+++ b/repo-config.yaml
@@ -2,7 +2,7 @@ apiVersion: v1
 kind: ConfigMap
 metadata:
   name: repo
-  namespace: system
+  namespace: weavek8sops
 data:
   kubernetes.repo: |
     [kubernetes]
diff --git a/wks-controller.yaml b/wks-controller.yaml
index 108bc10..9777cb4 100644
--- a/wks-controller.yaml
+++ b/wks-controller.yaml
@@ -3,7 +3,7 @@ apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: wks-controller
-  namespace: system
+  namespace: weavek8sops
   labels:
     name: wks-controller
     control-plane: wks-controller
```

```
E0913 16:07:20.998038       1 controller.go:160] Error checking existence of machine instance for machine object worker-0; failed to establish connection to machine worker-0: failed to read SSH key: failed to get WKS' secret: secrets "wks-controller-secrets" not found
```

**Comment by palemtnrider** [comment]
The node doesn't come up because the controller is unable to talk to the machine
>time="2019-09-19T19:05:15Z" level=info msg="checking existence of machine..." cluster=example machine=master-0
time="2019-09-19T19:05:15Z" level=error msg="failed to check existence of machine: failed to establish connection to machine master-0: failed to read SSH key: failed to get WKS' secret: secrets \"wks-controller-secrets\" not found" cluster=example machine=master-0
E0919 19:05:15.604579       1 controller.go:160] Error checking existence of machine instance for machine object master-0; failed to establish connection to machine master-0: failed to read SSH key: failed to get WKS' secret: secrets "wks-controller-secrets" not found
marks-MBP% kubectl describe deployment/wks-controller -n weavek8sops

**Comment by dlespiau** [comment]
I have seen this error and I believe it to be a separate issue: it happens "from time to time" re-running `setup.sh` makes it go away. Logged it at https://github.com/weaveworks/wksctl/issues/63.

Not sure what happens there, I was thinking we should add the ns to the log, we may be trying to get the secret in the wrong ns.

**Comment by palemtnrider** [comment]
> Not sure what happens there, I was thinking we should add the ns to the log, we may be trying to get the secret in the wrong ns.
My thoughts as well.  I'm chasing it a bit more.  We are pulling the ns from the machines and they are in the `default` namespace which is part of the problem.

**Comment by palemtnrider** [comment]
Figured out that the image override was always overriding this.  It is fixed in wksctl.
